### PR TITLE
Add some tones for audio testing.

### PR DESCRIPTION
**Pull request by pavelmachek**
Sooner or later phone will need to produce some sounds. Add some tones for testing.

### CODE REVIEW

**Comment by pavelmachek** [comment]
Aha, and I added some wallpapers, too. I thought I'd have to create separate pull request, but github merged them into one.

**Comment by ollieparanoid** [comment]
Stupid question, but how am I supposed to play the `.mid` files? I've tried with `audacious`, but it didn't make any sound. Also how about providing ogg files for example? I think we will also run into problems with playing them on the devices, or not?

**Comment by pavelmachek** [comment]
.mid files are midi -- kind of source format for a music. It is
possible to edit it, and it has to be "compiled" for playback. It is
also very compact, unlike .wav and .ogg.

[So I believe it is suitable for storage in .git.]

If you want to play it back, "timidity" is tool to use.

I'm not yet sure what formats we want to use on devices. On classic
phones, midi was popular (because it is small). We may want to
"compile" it to .wav/.ogg during the build. Not sure about that.

**Comment by ollieparanoid** [comment]
Thanks for the explanation!

`TiMidity++ version 2.14.0` gives me `No instrument mapped to tone bank 0, program 0 - this instrument will not be heard` and then silence for 3 or 4 seconds, depending on the file.

So I can't test this :-\ this might be a problem on my PC though, maybe someone else can try it?

**Comment by pavelmachek** [comment]
MIDI is a bit tricky. One solution is to use
https://onlinesequencer.net/ ... import MIDI files there. You'll need
to match instruments by names during import. That is what I used to
create the files.

**Comment by MartijnBraam** [comment]
I've converted the files to wav/opus manually with the soundfont and synth included in the arch repositories (timidity++ and freepats)

[sounds.zip](https://github.com/postmarketOS/artwork/files/1286126/sounds.zip)

**Comment by ollieparanoid** [comment]
Thanks for converting the files @MartijnBraam! In my personal opinion as non-sound expert, I think the startup sound sounds a bit "sad". But anyway, you mentioned sounds for testing - and for that they are more than enough! Thanks for sharing @pavelmachek!

**Pull request merged**
